export type AdminModuleKey =
  | "orders"
  | "quotes"
  | "invoices"
  | "fileUploads"
  | "coupons"
  | "reviews"
  | "newsletter"
  | "newsletterCampaigns"
  | "shipping"
  | "paymentMethods"
  | "usersRoles"
  | "emailTemplates"
  | "activityLogs"
  | "backups"
  | "security"
  | "categories"
  | "industries"
  | "products"
  | "studentArticles"
  | "studentVerifications"
  | "audit"
  | "crm-pending";

export type ModulePermission = "view" | "create" | "update" | "delete";
